/**
	Project Name:	LakeRidge Hospital
	Course:			DBAS 5206-06
	Group:			7
	Members:		Samuel Jeremiah Kayongo-Mutumba Jr
					Katherine Bellman
					Sanjivkumar Patel
	Date:			March 22th 2022
	Title:			Create Table Scripts
	Purpose:		Create The tables nessessary to host the hospital system
					Initialize all the dependencies, data types and relationships of tables
					Initialize table behaviour
**/

---DROP DATABASE
DROP DATABASE IF EXISTS LakeRidgeHospital
GO
CREATE DATABASE LakeRidgeHospital
GO

USE LakeRidgeHospital
GO
---CREATE TABLES

-- Create table to hold financial status providers
CREATE TABLE LakeRidgeHospital.dbo.FINANCIAL_STATUS
(
	STATUS_ID SMALLINT IDENTITY(100, 1) PRIMARY KEY,
	PROVIDER VARCHAR(30) NOT NULL,
)

-- Create table of transactions made
CREATE TABLE LakeRidgeHospital.dbo.CHARGE_TRANSACTION
(
	TRANSACTION_NUMBER INT IDENTITY(1000,1) PRIMARY KEY,
	STATUS_ID SMALLINT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.FINANCIAL_STATUS(STATUS_ID) NOT NULL,
	DATE DATETIME NOT NULL,
	PAID money NOT NULL,
)

-- Create table of Patients
CREATE TABLE LakeRidgeHospital.dbo.PATIENT
(
	PATIENT_NUMBER INT IDENTITY(100000,1) PRIMARY KEY,
	PATIENT_NAME VARCHAR(40) NOT NULL,
	PATIENT_ADDRESS VARCHAR(25) NOT NULL,
	CITY	VARCHAR(15) NOT NULL,
	PROVINCE CHAR(2) NOT NULL,
	POSTAL_CODE CHAR(7) NOT NULL,
	TELEPHONE CHAR(12) NOT NULL,
	SEX VARCHAR(6) NOT NULL,
	STATUS_ID SMALLINT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.FINANCIAL_STATUS(STATUS_ID) NOT NULL,

)

-- Create table of appointments
CREATE TABLE LakeRidgeHospital.dbo.APPOINTMENT
(
	APPOINTMENT_NUMBER INT IDENTITY(100000000, 1) PRIMARY KEY,
	PATIENT_NUMBER INT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.PATIENT(PATIENT_NUMBER) NOT NULL,
	TIME DATETIME NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL, 
)

-- Create table of types of users 
CREATE TABLE LakeRidgeHospital.dbo.USER_TYPE
(
	USER_TYPE_NUMBER SMALLINT IDENTITY(1,1) PRIMARY KEY,
	USER_TYPE VARCHAR(10) NOT NULL,
)

-- Create table of users
CREATE TABLE LakeRidgeHospital.dbo.DB_USER
(
	USER_ID INT IDENTITY(100, 1) PRIMARY KEY,
	USER_TYPE_NUMBER SMALLINT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.USER_TYPE(USER_TYPE_NUMBER) NOT NULL,
	PASSWORD CHAR(40) NOT NULL,
)

-- Create table of different specialities
CREATE TABLE LakeRidgeHospital.dbo.PHYSICIAN_SPECIALTY
(
	SPECIALTY_ID VARCHAR(3) PRIMARY KEY NOT NULL,
	SPECIALTY VARCHAR(25) NOT NULL,
)

-- Create table of physicians
CREATE TABLE LakeRidgeHospital.dbo.PHYSICIAN
(
	PHYSICIAN_NUMBER INT IDENTITY(100,1) PRIMARY KEY,
	USER_ID INT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.DB_USER(USER_ID) NOT NULL,
	PHYSICIAN_NAME VARCHAR(40) NOT NULL,
	TELEPHONE CHAR(12) NOT NULL,
	SPECIALTY_ID VARCHAR(3) FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.PHYSICIAN_SPECIALTY(SPECIALTY_ID) NOT NULL,

)

-- Create table of diagnosis
CREATE TABLE LakeRidgeHospital.dbo.DIAGNOSIS
(
	DIAGNOSIS_NUMBER INT IDENTITY(100,1) PRIMARY KEY,
	DIAGNOSIS VARCHAR(200) NOT NULL,
)

-- Create table of treatment
CREATE TABLE LakeRidgeHospital.dbo.TREATMENT
(
	TREATMENT_NUMBER INT IDENTITY(100000000, 1) PRIMARY KEY,
	DIAGNOSIS_NUMBER INT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.DIAGNOSIS(DIAGNOSIS_NUMBER) NOT NULL,
	PHYSICIAN_NUMBER INT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.PHYSICIAN(PHYSICIAN_NUMBER) NOT NULL,
	PATIENT_NUMBER INT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.PATIENT(PATIENT_NUMBER) NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL,
)

-- Create table of room types
CREATE TABLE LakeRidgeHospital.dbo.ROOM_TYPE
(
	ROOM_TYPE_ID CHAR(2) PRIMARY KEY,
	DESCRIPTION VARCHAR(20) NOT NULL,
)

-- Create table of rooms 
CREATE TABLE LakeRidgeHospital.dbo.ROOM
(
	ROOM_NUMBER SMALLINT PRIMARY KEY,
	ROOM_TYPE_NUMBER CHAR(2) FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.ROOM_TYPE(ROOM_TYPE_ID) NOT NULL,
)

-- Create table of beds
CREATE TABLE LakeRidgeHospital.dbo.BED
(
	ROOM_NUMBER SMALLINT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.ROOM(ROOM_NUMBER) NOT NULL,
	BED_CHAR CHAR NOT NULL,
	EXTENSION SMALLINT NOT NULL,
	PRIMARY KEY (ROOM_NUMBER, BED_CHAR),

)

-- Create table to contain admissions
CREATE TABLE LakeRidgeHospital.dbo.ADMISSION
(
	ADMISSION_NUMBER INT IDENTITY(1000000,1) PRIMARY KEY,
	PATIENT_NUMBER INT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.PATIENT(PATIENT_NUMBER) NOT NULL,
	DATE_ADMITTED DATETIME NOT NULL,
	DATE_DISCHARGED DATETIME,
	ROOM_NUMBER SMALLINT NOT NULL,
	BED_CHAR CHAR NOT NULL,
	FOREIGN KEY(ROOM_NUMBER, BED_CHAR) REFERENCES LakeRidgeHospital.dbo.BED(ROOM_NUMBER, BED_CHAR),
)

-- Create table of cost centers
CREATE TABLE LakeRidgeHospital.dbo.COST_CENTER 
(
	COST_CENTER_NUMBER TINYINT IDENTITY(1,1) PRIMARY KEY,
	DEPARTMENT_NAME VARCHAR(200) NOT NULL,

)

-- Create table of items
CREATE TABLE LakeRidgeHospital.dbo.ITEM
(
	ITEM_CODE INT IDENTITY (100,1) PRIMARY KEY,
	COST_CENTER_NUMBER TINYINT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.COST_CENTER(COST_CENTER_NUMBER) NOT NULL,
	DESCRIPTION VARCHAR(30) NOT NULL,
--It is important to note all charges are recorded in CAD$ 
	CHARGE smallmoney NOT NULL,
)

-- Create table of charges
CREATE TABLE LakeRidgeHospital.dbo.CHARGE
(
	CHARGE_NUMBER INT IDENTITY(100000,1) PRIMARY KEY,
	ADMISSION_NUMBER INT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.ADMISSION(ADMISSION_NUMBER) NOT NULL,
	ITEM_CODE INT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.ITEM(ITEM_CODE) NOT NULL,
	QUANTITY TINYINT NOT NULL,
	DATE_CHARGED DATETIME NOT NULL,
)

-- Create table of notes
CREATE TABLE LakeRidgeHospital.dbo.NOTE
(
	NOTE_NUMBER BIGINT IDENTITY(1,1) PRIMARY KEY,
	ADMISSION_NUMBER INT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.ADMISSION(ADMISSION_NUMBER) NOT NULL,
	ENTRY VARCHAR(200) NOT NULL,
)

-- Create table of admissions related to patients
CREATE TABLE LakeRidgeHospital.dbo.ADMISSION_LINE_ITEM
(
	ADMISSION_NUMBER INT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.ADMISSION(ADMISSION_NUMBER) NOT NULL,
	PATIENT_NUMBER INT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.PATIENT(PATIENT_NUMBER) NOT NULL,

	PRIMARY KEY(ADMISSION_NUMBER,PATIENT_NUMBER),
)

--Create table of bills
CREATE TABLE BILL(
	BILL_NUMBER BIGINT IDENTITY(1000,1) PRIMARY KEY,
	DATE_MADE DATETIME NOT NULL,
)

--Create table for bill items
CREATE TABLE BILL_LINE_ITEM (
	CHARGE_NUMBER INT  FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.CHARGE(CHARGE_NUMBER) NOT NULL,
	BILL_NUMBER BIGINT FOREIGN KEY REFERENCES BILL(BILL_NUMBER) NOT NULL,
	
	PRIMARY KEY(CHARGE_NUMBER, BILL_NUMBER),
)

-- Create table of charges assocaited with transactions 
CREATE TABLE LakeRidgeHospital.dbo.TRANSACTION_LINE_ITEM(
	TRANSACTION_NUMBER INT FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.CHARGE_TRANSACTION(TRANSACTION_NUMBER) NOT NULL,
	CHARGE_NUMBER INT  FOREIGN KEY REFERENCES LakeRidgeHospital.dbo.CHARGE(CHARGE_NUMBER) NOT NULL,

	PRIMARY KEY(TRANSACTION_NUMBER, CHARGE_NUMBER),
)
CREATE   PROCEDURE [dbo].[Search_By_Patient_History]
AS
BEGIN
	SELECT PATIENT_NUMBER,PATIENT_NAME,  PATIENT_ADDRESS 
	FROM PATIENT
	JOIN PHYSICIAN ON PATIENT.PATIENT_NUMBER = PHYSICIAN.PHYSICIAN_NUMBER

END
GO

EXEC Search_By_Patient_History;

CREATE   PROCEDURE [dbo].[Search_By_Note_From_Physician]

AS
BEGIN
	SELECT PATIENT_NUMBER,PATIENT_NAME,  PATIENT_ADDRESS ,CITY, SEX, STATUS_ID
	FROM PATIENT
	JOIN NOTE ON NOTE.NOTE_NUMBER = PATIENT.PATIENT_NUMBER
	JOIN PHYSICIAN ON NOTE.NOTE_NUMBER = PHYSICIAN.PHYSICIAN_NUMBER
	 

END
GO
EXEC Search_By_Note_From_Physician;


CREATE   PROCEDURE [dbo].[Search_By_Updated_Patient_Record]
AS
BEGIN
	SELECT PATIENT_NUMBER,PATIENT_NAME,  PATIENT_ADDRESS 
	FROM PATIENT
	SELECT PHYSICIAN_NAME, PHYSICIAN_NUMBER, SPECIALTY_ID
	FROM PHYSICIAN
	JOIN DIAGNOSIS ON DIAGNOSIS.DIAGNOSIS_NUMBER = PATIENT.PATIENT_NUMBER
	JOIN PHYSICIAN ON NOTE.NOTE_NUMBER = PHYSICIAN.PHYSICIAN_NUMBER
	 

END
GO

